/*
 * This file is generated by jOOQ.
*/
package com.example.app.products.jooq;


import com.example.app.products.jooq.tables.Account;
import com.example.app.products.jooq.tables.Download;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>products_download</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_PRIMARY = Indexes0.ACCOUNT_PRIMARY;
    public static final Index ACCOUNT_UK_Q0UJA26QGU1ATULENWUP9RXYR = Indexes0.ACCOUNT_UK_Q0UJA26QGU1ATULENWUP9RXYR;
    public static final Index DOWNLOAD_COMMENTS_ACCOUNT_FK = Indexes0.DOWNLOAD_COMMENTS_ACCOUNT_FK;
    public static final Index DOWNLOAD_PRIMARY = Indexes0.DOWNLOAD_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_PRIMARY = Internal.createIndex("PRIMARY", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.ID }, true);
        public static Index ACCOUNT_UK_Q0UJA26QGU1ATULENWUP9RXYR = Internal.createIndex("UK_q0uja26qgu1atulenwup9rxyr", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.EMAIL }, true);
        public static Index DOWNLOAD_COMMENTS_ACCOUNT_FK = Internal.createIndex("comments_account_FK", Download.DOWNLOAD, new OrderField[] { Download.DOWNLOAD.DOWNLOADED_BY }, false);
        public static Index DOWNLOAD_PRIMARY = Internal.createIndex("PRIMARY", Download.DOWNLOAD, new OrderField[] { Download.DOWNLOAD.ID }, true);
    }
}
