/*
 * This file is generated by jOOQ.
*/
package com.example.app.products.jooq;


import com.example.app.products.jooq.tables.Account;
import com.example.app.products.jooq.tables.Download;
import com.example.app.products.jooq.tables.records.AccountRecord;
import com.example.app.products.jooq.tables.records.DownloadRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>products_download</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DownloadRecord, UInteger> IDENTITY_DOWNLOAD = Identities0.IDENTITY_DOWNLOAD;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_PRIMARY = UniqueKeys0.KEY_ACCOUNT_PRIMARY;
    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_UK_Q0UJA26QGU1ATULENWUP9RXYR = UniqueKeys0.KEY_ACCOUNT_UK_Q0UJA26QGU1ATULENWUP9RXYR;
    public static final UniqueKey<DownloadRecord> KEY_DOWNLOAD_PRIMARY = UniqueKeys0.KEY_DOWNLOAD_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DownloadRecord, AccountRecord> COMMENTS_ACCOUNT_FK = ForeignKeys0.COMMENTS_ACCOUNT_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DownloadRecord, UInteger> IDENTITY_DOWNLOAD = Internal.createIdentity(Download.DOWNLOAD, Download.DOWNLOAD.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> KEY_ACCOUNT_PRIMARY = Internal.createUniqueKey(Account.ACCOUNT, "KEY_account_PRIMARY", Account.ACCOUNT.ID);
        public static final UniqueKey<AccountRecord> KEY_ACCOUNT_UK_Q0UJA26QGU1ATULENWUP9RXYR = Internal.createUniqueKey(Account.ACCOUNT, "KEY_account_UK_q0uja26qgu1atulenwup9rxyr", Account.ACCOUNT.EMAIL);
        public static final UniqueKey<DownloadRecord> KEY_DOWNLOAD_PRIMARY = Internal.createUniqueKey(Download.DOWNLOAD, "KEY_download_PRIMARY", Download.DOWNLOAD.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<DownloadRecord, AccountRecord> COMMENTS_ACCOUNT_FK = Internal.createForeignKey(com.example.app.products.jooq.Keys.KEY_ACCOUNT_UK_Q0UJA26QGU1ATULENWUP9RXYR, Download.DOWNLOAD, "comments_account_FK", Download.DOWNLOAD.DOWNLOADED_BY);
    }
}
