/*
 * This file is generated by jOOQ.
*/
package com.example.app.products.jooq;


import com.example.app.products.jooq.tables.Account;
import com.example.app.products.jooq.tables.Download;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsDownload extends SchemaImpl {

    private static final long serialVersionUID = -1614086406;

    /**
     * The reference instance of <code>products_download</code>
     */
    public static final ProductsDownload PRODUCTS_DOWNLOAD = new ProductsDownload();

    /**
     * The table <code>products_download.account</code>.
     */
    public final Account ACCOUNT = com.example.app.products.jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>products_download.download</code>.
     */
    public final Download DOWNLOAD = com.example.app.products.jooq.tables.Download.DOWNLOAD;

    /**
     * No further instances allowed
     */
    private ProductsDownload() {
        super("products_download", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Download.DOWNLOAD);
    }
}
