/*
 * This file is generated by jOOQ.
*/
package com.example.app.products.jooq;


import com.example.app.products.jooq.tables.Account;
import com.example.app.products.jooq.tables.Download;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in products_download
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>products_download.account</code>.
     */
    public static final Account ACCOUNT = com.example.app.products.jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>products_download.download</code>.
     */
    public static final Download DOWNLOAD = com.example.app.products.jooq.tables.Download.DOWNLOAD;
}
