/*
 * This file is generated by jOOQ.
*/
package com.example.app.products.jooq.tables.records;


import com.example.app.products.jooq.tables.Download;
import com.example.app.products.jooq.tables.interfaces.IDownload;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DownloadRecord extends UpdatableRecordImpl<DownloadRecord> implements VertxPojo, Record5<UInteger, String, Timestamp, String, String>, IDownload {

    private static final long serialVersionUID = 1234324078;

    /**
     * Setter for <code>products_download.download.id</code>.
     */
    @Override
    public DownloadRecord setId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>products_download.download.id</code>.
     */
    @Override
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>products_download.download.product_name</code>.
     */
    @Override
    public DownloadRecord setProductName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>products_download.download.product_name</code>.
     */
    @Override
    public String getProductName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>products_download.download.download_date</code>.
     */
    @Override
    public DownloadRecord setDownloadDate(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>products_download.download.download_date</code>.
     */
    @Override
    public Timestamp getDownloadDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>products_download.download.comment_link</code>.
     */
    @Override
    public DownloadRecord setCommentLink(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>products_download.download.comment_link</code>.
     */
    @Override
    public String getCommentLink() {
        return (String) get(3);
    }

    /**
     * Setter for <code>products_download.download.downloaded_by</code>.
     */
    @Override
    public DownloadRecord setDownloadedBy(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>products_download.download.downloaded_by</code>.
     */
    @Override
    public String getDownloadedBy() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, Timestamp, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, Timestamp, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Download.DOWNLOAD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Download.DOWNLOAD.PRODUCT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Download.DOWNLOAD.DOWNLOAD_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Download.DOWNLOAD.COMMENT_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Download.DOWNLOAD.DOWNLOADED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProductName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getDownloadDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCommentLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDownloadedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProductName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getDownloadDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCommentLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDownloadedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DownloadRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DownloadRecord value2(String value) {
        setProductName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DownloadRecord value3(Timestamp value) {
        setDownloadDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DownloadRecord value4(String value) {
        setCommentLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DownloadRecord value5(String value) {
        setDownloadedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DownloadRecord values(UInteger value1, String value2, Timestamp value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IDownload from) {
        setId(from.getId());
        setProductName(from.getProductName());
        setDownloadDate(from.getDownloadDate());
        setCommentLink(from.getCommentLink());
        setDownloadedBy(from.getDownloadedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IDownload> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DownloadRecord
     */
    public DownloadRecord() {
        super(Download.DOWNLOAD);
    }

    /**
     * Create a detached, initialised DownloadRecord
     */
    public DownloadRecord(UInteger id, String productName, Timestamp downloadDate, String commentLink, String downloadedBy) {
        super(Download.DOWNLOAD);

        set(0, id);
        set(1, productName);
        set(2, downloadDate);
        set(3, commentLink);
        set(4, downloadedBy);
    }

    public DownloadRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
