/*
 * This file is generated by jOOQ.
*/
package com.example.app.products.jooq.tables.pojos;


import com.example.app.products.jooq.tables.interfaces.IAccount;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements VertxPojo, IAccount {

    private static final long serialVersionUID = 524938346;

    private Long      id;
    private Timestamp created;
    private String    email;
    private String    password;
    private String    role;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.created = value.created;
        this.email = value.email;
        this.password = value.password;
        this.role = value.role;
    }

    public Account(
        Long      id,
        Timestamp created,
        String    email,
        String    password,
        String    role
    ) {
        this.id = id;
        this.created = created;
        this.email = email;
        this.password = password;
        this.role = role;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public Account setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public Timestamp getCreated() {
        return this.created;
    }

    @Override
    public Account setCreated(Timestamp created) {
        this.created = created;
        return this;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public Account setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public Account setPassword(String password) {
        this.password = password;
        return this;
    }

    @Override
    public String getRole() {
        return this.role;
    }

    @Override
    public Account setRole(String role) {
        this.role = role;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(created);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IAccount from) {
        setId(from.getId());
        setCreated(from.getCreated());
        setEmail(from.getEmail());
        setPassword(from.getPassword());
        setRole(from.getRole());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IAccount> E into(E into) {
        into.from(this);
        return into;
    }

    public Account(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
