/*
 * This file is generated by jOOQ.
*/
package com.example.app.products.jooq.tables.pojos;


import com.example.app.products.jooq.tables.interfaces.IDownload;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Download implements VertxPojo, IDownload {

    private static final long serialVersionUID = 1381606951;

    private UInteger  id;
    private String    productName;
    private Timestamp downloadDate;
    private String    commentLink;
    private String    downloadedBy;

    public Download() {}

    public Download(Download value) {
        this.id = value.id;
        this.productName = value.productName;
        this.downloadDate = value.downloadDate;
        this.commentLink = value.commentLink;
        this.downloadedBy = value.downloadedBy;
    }

    public Download(
        UInteger  id,
        String    productName,
        Timestamp downloadDate,
        String    commentLink,
        String    downloadedBy
    ) {
        this.id = id;
        this.productName = productName;
        this.downloadDate = downloadDate;
        this.commentLink = commentLink;
        this.downloadedBy = downloadedBy;
    }

    @Override
    public UInteger getId() {
        return this.id;
    }

    @Override
    public Download setId(UInteger id) {
        this.id = id;
        return this;
    }

    @Override
    public String getProductName() {
        return this.productName;
    }

    @Override
    public Download setProductName(String productName) {
        this.productName = productName;
        return this;
    }

    @Override
    public Timestamp getDownloadDate() {
        return this.downloadDate;
    }

    @Override
    public Download setDownloadDate(Timestamp downloadDate) {
        this.downloadDate = downloadDate;
        return this;
    }

    @Override
    public String getCommentLink() {
        return this.commentLink;
    }

    @Override
    public Download setCommentLink(String commentLink) {
        this.commentLink = commentLink;
        return this;
    }

    @Override
    public String getDownloadedBy() {
        return this.downloadedBy;
    }

    @Override
    public Download setDownloadedBy(String downloadedBy) {
        this.downloadedBy = downloadedBy;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Download (");

        sb.append(id);
        sb.append(", ").append(productName);
        sb.append(", ").append(downloadDate);
        sb.append(", ").append(commentLink);
        sb.append(", ").append(downloadedBy);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IDownload from) {
        setId(from.getId());
        setProductName(from.getProductName());
        setDownloadDate(from.getDownloadDate());
        setCommentLink(from.getCommentLink());
        setDownloadedBy(from.getDownloadedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IDownload> E into(E into) {
        into.from(this);
        return into;
    }

    public Download(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
