/*
 * This file is generated by jOOQ.
*/
package com.example.app.products.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAccount extends VertxPojo, Serializable {

    /**
     * Setter for <code>products_download.account.id</code>.
     */
    public IAccount setId(Long value);

    /**
     * Getter for <code>products_download.account.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>products_download.account.created</code>.
     */
    public IAccount setCreated(Timestamp value);

    /**
     * Getter for <code>products_download.account.created</code>.
     */
    public Timestamp getCreated();

    /**
     * Setter for <code>products_download.account.email</code>.
     */
    public IAccount setEmail(String value);

    /**
     * Getter for <code>products_download.account.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>products_download.account.password</code>.
     */
    public IAccount setPassword(String value);

    /**
     * Getter for <code>products_download.account.password</code>.
     */
    public String getPassword();

    /**
     * Setter for <code>products_download.account.role</code>.
     */
    public IAccount setRole(String value);

    /**
     * Getter for <code>products_download.account.role</code>.
     */
    public String getRole();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IAccount
     */
    public void from(com.example.app.products.jooq.tables.interfaces.IAccount from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IAccount
     */
    public <E extends com.example.app.products.jooq.tables.interfaces.IAccount> E into(E into);

    @Override
    public default IAccount fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getLong("id"));
        // Omitting unrecognized type java.sql.Timestamp for column created!
        setEmail(json.getString("email"));
        setPassword(json.getString("password"));
        setRole(json.getString("role"));
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        // Omitting unrecognized type java.sql.Timestamp for column created!
        json.put("email",getEmail());
        json.put("password",getPassword());
        json.put("role",getRole());
        return json;
    }

}
